"""empty message

Revision ID: 51b43e81926
Revises: None
Create Date: 2015-10-05 18:57:56.907094

"""

# revision identifiers, used by Alembic.
revision = '51b43e81926'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    ### end Alembic commands ###
